version: "3.8"

services:
  registry:
    image: registry:2.8.2
    container_name: registry
    restart: unless-stopped
    environment:
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: '[https://${REGISTRY_DOMAIN}]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '[HEAD,GET,OPTIONS,DELETE]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: '[true]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '[Authorization,Accept,Cache-Control]'
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '[Docker-Content-Digest]'
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    volumes:
      - ./data:/var/lib/registry
      - ./auth:/auth
      - ./certs:/certs
    networks:
      - registry_net

  registry-ui:
    image: joxit/docker-registry-ui:main
    container_name: registry-ui
    depends_on:
      - registry
    restart: unless-stopped
    environment:
      SINGLE_REGISTRY: "true"
      REGISTRY_TITLE: "HeyTrip Private Registry"
      DELETE_IMAGES: "true"
      SHOW_CONTENT_DIGEST: "true"
      REGISTRY_SECURED: "true"
      REGISTRY_TRUST_ANY_CERTS: "true"
      REGISTRY_URL: "https://${REGISTRY_DOMAIN}/registry"
      SHOW_CATALOG_NB_TAGS: "true"
      CATALOG_MIN_BRANCHES: "1"
      CATALOG_MAX_BRANCHES: "1"
      TAGLIST_PAGE_SIZE: "100"
      CATALOG_ELEMENTS_LIMIT: "1000"
      THEME: "dark"
    networks:
      - registry_net

networks:
  registry_net:
    name: registry_net
    driver: bridge
